[biophysical_constants]
transcription_saturation_constant=0.036                # units: µM
characteristic_transcript_length=1000                  # units: nt 
energy_promoter_state_1=20.0                           # units: kJ/mol
energy_promoter_state_2=-28.8                          # units: kJ/mol
inducer_dissociation_constant="need_to_fill_me_in"      # units: muM
inducer_cooperativity_parameter="need_to_fill_me_in"    # units: dimensionless
mRNA_half_life_in_min = "need_to_fill_me_in"            # units: hr
RNAPII_concentration="need_to_fill_me_in"               # units: µM
transcription_elongation_rate="need_to_fill_me_in"      # units: nt/s
transcription_time_constant="need_to_fill_me_in"        # units: dimensionless
gene_length_in_nt="need_to_fill_me_in"                  # units: nt
